local debug_adapters = {
  go = 'delve',
  dotnet = 'netcoredbg',
  python = 'debugpy',
  javascript = 'js-debug-adapter',
  rust = 'codelldb',
}

return {
  -- Mason's upstream recipe still ships an Intel-only macOS build.
  netcoredbg_version = (vim.fn.has 'macunix' == 1 and vim.uv.os_uname().machine == 'x86_64') and '3.1.3-1062' or '3.2.0-1092',
  debug_adapters = debug_adapters,
  mason = {
    debug_adapters.go,
    debug_adapters.python,
    debug_adapters.javascript,
    debug_adapters.rust,
    'eslint-lsp',
    'goimports',
    'gopls',
    'java-debug-adapter',
    'java-test',
    'jdtls',
    'jinja-lsp',
    'json-lsp',
    'lua-language-server',
    debug_adapters.dotnet,
    'oxfmt',
    'prettier',
    'puppet-editor-services',
    'pyright',
    'roslyn',
    'ruff',
    'rust-analyzer',
    'sqlls',
    'stylua',
    'terraform-ls',
    'typescript-language-server',
    'vue-language-server',
    'zls',
  },
  -- Specialised plugins own Java, C# and Rust. Formatters run via Conform.
  lsp = {
    'eslint',
    'gopls',
    'jinja_lsp',
    'jsonls',
    'lua_ls',
    'puppet',
    'pyright',
    'ruff',
    'sqlls',
    'terraformls',
    'ts_ls',
    'vue_ls',
    'zls',
  },
  treesitter = {
    'bash',
    'c',
    'c_sharp',
    'css',
    'diff',
    'dockerfile',
    'gitignore',
    'git_rebase',
    'go',
    'graphql',
    'groovy',
    'hcl',
    'html',
    'ini',
    'java',
    'javascript',
    'jinja',
    'jinja_inline',
    'json',
    'lua',
    'luadoc',
    'markdown',
    'markdown_inline',
    'powershell',
    'proto',
    'puppet',
    'python',
    'query',
    'rust',
    'sql',
    'toml',
    'tsx',
    'typescript',
    'vim',
    'vimdoc',
    'vue',
    'xml',
    'yaml',
    'zig',
    'zsh',
  },
}
