local debug_adapters = {
  go = 'delve',
  dotnet = 'netcoredbg',
}

return {
  debug_adapters = debug_adapters,
  mason = {
    debug_adapters.go,
    'eslint-lsp',
    'goimports',
    'gopls',
    'java-debug-adapter',
    'java-test',
    'jdtls',
    'jinja-lsp',
    'json-lsp',
    'lua-language-server',
    debug_adapters.dotnet,
    'oxfmt',
    'prettier',
    'puppet-editor-services',
    'pyright',
    'roslyn',
    'ruff',
    'rust-analyzer',
    'sqlls',
    'stylua',
    'terraform-ls',
    'typescript-language-server',
    'vue-language-server',
    'zls',
  },
  mason_dap = {
    debug_adapters.go,
  },
  treesitter = {
    'bash',
    'c',
    'c_sharp',
    'css',
    'diff',
    'dockerfile',
    'gitignore',
    'git_rebase',
    'go',
    'graphql',
    'groovy',
    'html',
    'ini',
    'javascript',
    'jinja',
    'jinja_inline',
    'json',
    'lua',
    'luadoc',
    'markdown',
    'markdown_inline',
    'powershell',
    'proto',
    'puppet',
    'python',
    'query',
    'rust',
    'sql',
    'toml',
    'tsx',
    'typescript',
    'vim',
    'vimdoc',
    'xml',
    'yaml',
    'zsh',
  },
}
